---
- name: Install RHEL package
  yum:
    name: "{{ package_url }}"
    state: present
    disable_gpg_check: true
  when: 
  - ansible_os_family == "RedHat"
  notify: "restart bindplane agent"

- name: Install SUSE package
  zypper:
    name: "{{ package_url }}"
    state: present
    disable_gpg_check: true
  when: 
  - ansible_os_family == "Suse"
  notify: "restart bindplane agent"

- name: Install Debian package
  apt:
    deb: "{{ package_url }}"
    state: present
  when: 
  - ansible_os_family == 'Debian'
  notify: "restart bindplane agent"

- name: Create observiq-otel-collector.service.d directory
  file:
    path: /etc/systemd/system/observiq-otel-collector.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

# Use environment variables to configure OpAMP instead of writing
# a manager.yaml. This allows the BindPlane OP server to push changes
# to the manager config without competing with Ansible.
- name: "Create systemd environment override"
  template:
    src: "override.conf.tmpl"
    dest: /etc/systemd/system/observiq-otel-collector.service.d/override.conf
    owner: root
    group: root
    mode: 0640
  notify: "restart bindplane agent"

