---
- name: Install RHEL package
  yum:
    name: "{{ package_url }}"
    state: present
    disable_gpg_check: true
  when: 
  - ansible_os_family == "RedHat"
  notify: "restart bindplane agent"

- name: Install SUSE package
  zypper:
    name: "{{ package_url }}"
    state: present
    disable_gpg_check: true
  when: 
  - ansible_os_family == "Suse"
  notify: "restart bindplane agent"

- name: Install Debian package
  apt:
    deb: "{{ package_url }}"
    state: present
  when: 
  - ansible_os_family == 'Debian'
  notify: "restart bindplane agent"

- name: "create manager.yaml"
  template:
    src: "manager.yaml.tmpl"
    dest: "{{ install_dir }}/manager.yaml"
    mode: 0640
  notify: "restart bindplane agent"

