---
# Verify the state of the VM after the role has finished executing.
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Call Linux specific playbook
      include_tasks: verify_linux.yml
      when: ansible_os_family in ['Debian', 'RedHat', 'Suse']

    #- name: Call Windows specific playbook
    #  include_tasks: verify_windows.yml
    #  when: ansible_os_family == 'Windows'
