---
# This file is the central configuration entrypoint for Molecule. With this file, you can configure each tool that Molecule will employ when testing the role.
dependency:
  name: galaxy
driver:
  name: delegated
  gcp_service_account_key: ${GOOGLE_APPLICATION_CREDENTIALS}
  gcp_project_id: ${GCP_PROJECT_ID}
  ssh_user: ${SSH_USER}
  zone: us-east1-b
  region: us-east1
lint: |
  set -e
  ansible-lint
platforms:
  - name: "rhel-9-${MOLECULE_SCENARIO_NAME}${GITHUB_RUN_ID}"
    image_family: projects/rhel-cloud/global/images/family/rhel-9
    machine_type: e2-small
    size_gb: 40
    preemptible: true
    groups:
      - linux
      - rhel
  - name: "debian-10-${MOLECULE_SCENARIO_NAME}${GITHUB_RUN_ID}"
    image_family: projects/debian-cloud/global/images/family/debian-11
    machine_type: e2-small
    size_gb: 40
    preemptible: true
    groups:
      - linux
      - debian
  - name: "sles-15-${MOLECULE_SCENARIO_NAME}${GITHUB_RUN_ID}"
    image_family: projects/suse-cloud/global/images/family/sles-15
    machine_type: e2-small
    size_gb: 40
    preemptible: true
    groups:
      - linux
      - sles
scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
provisioner:
  name: ansible
  inventory:
    group_vars:
      linux:
        ansible_ssh_private_key_file: ${SSH_KEY_FILE}
  playbooks:
    create: ../resources/create.yml
    converge: ./converge.yml
    verify: ../resources/verify.yml
    destroy: ../resources/destroy.yml
verifier:
  name: ansible
